# Generated by Django 5.2.1 on 2025-05-11 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_product_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technical',
            fields=[
            ],
            options={
                'verbose_name': 'Technical',
                'verbose_name_plural': 'Technicals',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.product',),
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
    ]
